remote_theme: "tareqdandachi/jekyll-shell-theme"

title: Wagner Wave
email: alexandre1.wagner@epitech.eu
description: >- # this means to ignore newlines until "baseurl:"
  wagnerwave - Webiste & Blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wagnerwave.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: toti
github_username:  wagnerwave

# Build settings
plugins: 
  - jekyll-remote-theme
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - blog.md
  - about.md
  - resume.md

# set the size of the text to 'large' or 'small', default is small
font-size: large